import { useEffect, useRef, type Dispatch, type KeyboardEvent } from 'react'
import { ArrowLeft, ArrowUpRight, BarChart3, CalendarDays, Check, LayoutDashboard, MessageCircle, RotateCcw, Users, X } from 'lucide-react'
import { demoClock, filterConsultations, formatDate, getCurrentCounts, getFunnel, getGroups, getPending, nextStage, stageLabels, type Consultation, type DemoAction, type DemoState, type Outcome, type Stage, type View } from './model'
import './demo.css'

type Props = { state: DemoState; dispatch: Dispatch<DemoAction> }
const views = [{ id: 'summary', label: 'Resumen', icon: LayoutDashboard }, { id: 'patients', label: 'Pacientes', icon: Users }, { id: 'pending', label: 'Pendientes', icon: CalendarDays }, { id: 'analysis', label: 'Análisis', icon: BarChart3 }] as const
const guide = ['Abrí la consulta señalada en Pendientes.', 'Elegí «Simular WhatsApp» para preparar el contacto.', 'Revisá el mensaje y pulsá «Simular envío».', 'Ahora elegí «Registrar resultado».', 'Seleccioná «Agendó cita», elegí fecha y hora y guardá.', 'Ahora la consulta tiene un próximo paso.']

function tabKey(event: KeyboardEvent<HTMLButtonElement>, index: number, count: number, select: (index: number) => void) {
  const next = event.key === 'ArrowRight' ? (index + 1) % count : event.key === 'ArrowLeft' ? (index + count - 1) % count : event.key === 'Home' ? 0 : event.key === 'End' ? count - 1 : null
  if (next !== null) { event.preventDefault(); select(next) }
}

function Funnel({ consultations }: { consultations: Consultation[] }) {
  const rows = getFunnel(consultations)
  return <div className="crm-funnel"><div className="crm-subheading"><h4>Embudo acumulado</h4><span>Etapas alcanzadas</span></div><p className="crm-muted">Una consulta conserva cada etapa alcanzada aunque avance o cierre su seguimiento.</p>{rows.map((row) => <div className="crm-bar-row" key={row.stage}><div><span>{row.label}</span><strong>{row.count}</strong></div><div className="crm-bar-track" aria-hidden="true"><span style={{ width: `${consultations.length ? row.count / consultations.length * 100 : 0}%` }} /></div><small>{row.count} de {row.denominator} · {row.percent}% {row.stage === 'lead' ? 'del total' : 'de la etapa anterior'}</small></div>)}</div>
}

export function HeroPreview({ state }: Pick<Props, 'state'>) {
  const funnel = getFunnel(state.consultations)
  return <div className="crm-preview"><div className="crm-preview-heading"><strong>DentFlow<span>Visión de tu operación</span></strong><span className="crm-badge">DEMO</span></div><div className="crm-preview-metrics"><div><span>Consultas</span><strong>{state.consultations.length}</strong></div><div><span>Por hacer</span><strong>{getPending(state.consultations).length}</strong></div><div><span>Agendaron</span><strong>{funnel[2].count}</strong></div></div><div className="crm-preview-bars">{funnel.slice(0, 5).map((row) => <div key={row.stage}><span>{row.label}</span><i style={{ width: `${row.count / state.consultations.length * 100}%` }} /><strong>{row.count}</strong></div>)}</div><a className="crm-preview-link" href="#demo-crm">Probá la demo interactiva <ArrowUpRight size={16} /></a></div>
}

function Summary({ state, dispatch }: Props) {
  const funnel = getFunnel(state.consultations)
  return <><div className="crm-metrics"><div><span>Consultas registradas</span><strong>{state.consultations.length}</strong><small>Datos de esta demo</small></div><div><span>Acciones pendientes</span><strong>{getPending(state.consultations).length}</strong><button onClick={() => dispatch({ type: 'navigate', view: 'pending' })}>Revisar pendientes →</button></div><div><span>Citas alcanzadas</span><strong>{funnel[2].count}</strong><small>{funnel[2].percent}% de las contactadas</small></div></div><div className="crm-summary-grid"><Funnel consultations={state.consultations} /><div><h4>Etapa actual</h4><p className="crm-muted">Cada consulta aparece una sola vez en esta lista.</p><dl className="crm-counts">{getCurrentCounts(state.consultations).map((row) => <div key={row.stage}><dt>{row.label}</dt><dd>{row.count}</dd></div>)}</dl></div></div></>
}

function PatientList({ state, dispatch, pending = false }: Props & { pending?: boolean }) {
  const rows = pending ? getPending(state.consultations) : filterConsultations(state.consultations, state.filters)
  return <>{!pending && <div className="crm-filters"><label className="crm-search">Buscar consulta<input type="search" placeholder="Nombre o teléfono ficticio" value={state.filters.search} onChange={(e) => dispatch({ type: 'filter', key: 'search', value: e.target.value })} /></label>{(['treatment', 'stage', 'source'] as const).map((key) => <label key={key}>{({ treatment: 'Tratamiento', stage: 'Estado', source: 'Fuente' })[key]}<select value={state.filters[key]} onChange={(e) => dispatch({ type: 'filter', key, value: e.target.value })}><option value="">Todos</option>{key === 'stage' ? Object.entries(stageLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>) : [...new Set(state.consultations.map((row) => row[key]))].map((value) => <option key={value}>{value}</option>)}</select></label>)}<button className="crm-button" onClick={() => dispatch({ type: 'clearFilters' })}>Limpiar filtros</button></div>}<div className="crm-subheading"><h4>{pending ? 'Próximas acciones' : 'Consultas'}</h4><span>{rows.length} {rows.length === 1 ? 'consulta' : 'consultas'}</span></div>{pending && <p className="crm-muted">Ordenadas por fecha de la próxima acción. Abrí una consulta para contactar o registrar el resultado.</p>}<div className="crm-patients">{rows.map((row) => <button id={`consultation-${row.id}`} className={`crm-patient${state.tour?.id === row.id && state.tour.step === 0 ? ' crm-guided' : ''}`} key={row.id} onClick={() => dispatch({ type: 'select', id: row.id })}><span className="crm-person"><strong>{row.name}</strong><small>{row.phone} · {row.treatment}</small></span><span><span className={`crm-stage ${row.stage === 'lost' ? 'crm-stage--lost' : row.stage === 'started' ? 'crm-stage--success' : ''}`}>{stageLabels[row.stage]}</span><small>{pending && row.nextAction ? row.nextAction.label : `${row.source} · ${row.owner}`}</small></span><span className="crm-patient-date">{row.nextAction ? formatDate(row.nextAction.dueAt) : 'Sin seguimiento'}<small>{pending && row.nextAction && row.nextAction.dueAt < demoClock(state) ? 'Vencida en la demo' : 'Próxima acción'} <ArrowUpRight size={14} /></small></span></button>)}</div>{rows.length === 0 && <div className="crm-empty"><Users size={28} /><h4>{pending ? 'No hay acciones pendientes.' : 'No encontramos consultas con esos filtros.'}</h4>{!pending && <button className="crm-button" onClick={() => dispatch({ type: 'clearFilters' })}>Limpiar filtros</button>}</div>}</>
}

function Analysis({ state, dispatch }: Props) {
  const tabs = [{ id: 'funnel', label: 'Embudo' }, { id: 'sources', label: 'Fuentes' }, { id: 'treatments', label: 'Tratamientos' }] as const
  const refs = useRef<(HTMLButtonElement | null)[]>([])
  return <><div className="crm-analysis-tabs" role="tablist" aria-label="Análisis por categoría">{tabs.map((tab, index) => <button key={tab.id} ref={(el) => { refs.current[index] = el }} id={`analysis-${tab.id}`} role="tab" aria-controls="analysis-panel" aria-selected={state.analysisTab === tab.id} tabIndex={state.analysisTab === tab.id ? 0 : -1} onClick={() => dispatch({ type: 'analysis', tab: tab.id })} onKeyDown={(e) => tabKey(e, index, tabs.length, (next) => { dispatch({ type: 'analysis', tab: tabs[next].id }); refs.current[next]?.focus() })}>{tab.label}</button>)}</div><div id="analysis-panel" role="tabpanel" aria-labelledby={`analysis-${state.analysisTab}`} tabIndex={0} key={state.analysisTab} className="crm-view">{state.analysisTab === 'funnel' ? <Funnel consultations={state.consultations} /> : <><h4>{state.analysisTab === 'sources' ? 'De dónde llegan las consultas' : 'Interés por tratamiento'}</h4><p className="crm-muted">Total de consultas y etapas alcanzadas dentro de cada grupo.</p><div className="crm-groups">{getGroups(state.consultations, state.analysisTab === 'sources' ? 'source' : 'treatment').map((group) => <div key={group.label}><div className="crm-subheading"><strong>{group.label}</strong><span>{group.total} consultas</span></div><div className="crm-bar-track" aria-hidden="true"><span style={{ width: `${group.total / state.consultations.length * 100}%` }} /></div><p>{group.contacted} contactadas · {group.scheduled} agendaron · {group.attended} asistieron</p></div>)}</div></>}</div></>
}

function Detail({ state, dispatch, consultation: row }: Props & { consultation: Consultation }) {
  const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { heading.current?.focus({ preventScroll: true }) }, [row.id])
  const closed = row.stage === 'lost' || row.stage === 'started'
  return <div className="crm-detail"><button className="crm-button" onClick={() => { dispatch({ type: 'closeDetail' }); requestAnimationFrame(() => document.getElementById(`consultation-${row.id}`)?.focus({ preventScroll: true })) }}><ArrowLeft size={16} /> Volver a la lista</button><div className="crm-detail-heading"><div><span className="crm-muted">{row.id} · {row.treatment}</span><h3 ref={heading} tabIndex={-1}>{row.name}</h3></div><span className="crm-stage">{stageLabels[row.stage]}</span></div><dl className="crm-details"><div><dt>Teléfono ficticio</dt><dd>{row.phone}</dd></div><div><dt>Fuente</dt><dd>{row.source}</dd></div><div><dt>Responsable</dt><dd>{row.owner}</dd></div><div><dt>Creación</dt><dd>{formatDate(row.createdAt)}</dd></div></dl><div className="crm-next"><CalendarDays size={22} /><div><strong>{row.nextAction?.label ?? 'Seguimiento cerrado'}</strong><p>{row.nextAction ? formatDate(row.nextAction.dueAt) : 'Esta consulta ya no tiene acciones pendientes.'}</p></div></div>{!closed && <div className="crm-actions"><button className={`crm-button crm-button--primary${state.tour?.step === 1 ? ' crm-guided' : ''}`} onClick={() => dispatch({ type: 'openModal', modal: 'contact' })}><MessageCircle size={17} /> Simular WhatsApp</button><button className={`crm-button${state.tour?.step === 3 ? ' crm-guided' : ''}`} onClick={() => dispatch({ type: 'openModal', modal: 'result' })}>Registrar resultado</button><button className="crm-button" onClick={() => dispatch({ type: 'openModal', modal: 'stage' })}>{row.stage === 'scheduled' ? 'Registrar asistencia' : 'Cambiar etapa'}</button></div>}<h4>Historial de la consulta</h4><ol className="crm-timeline">{[...row.history].reverse().map((event) => <li key={event.id}><time dateTime={event.at}>{formatDate(event.at)}</time><p>{event.text}</p></li>)}</ol></div>
}

function ActionDialog({ state, dispatch }: Props) {
  const dialog = useRef<HTMLDialogElement>(null)
  const row = state.consultations.find((item) => item.id === state.selectedId)
  useEffect(() => {
    const element = dialog.current
    if (!state.modal || !element) return
    const previous = document.activeElement as HTMLElement | null
    element.showModal()
    return () => { element.close(); if (previous?.isConnected) previous.focus({ preventScroll: true }); else document.querySelector<HTMLButtonElement>('.crm-nav [aria-selected="true"]')?.focus({ preventScroll: true }) }
  }, [state.modal, state.view])
  if (!row) return null
  const needsAppointment = state.modal === 'result' ? state.outcome === 'scheduled' : state.targetStage === 'scheduled'
  return <dialog ref={dialog} className="crm-dialog" aria-labelledby="crm-dialog-title" aria-describedby="crm-dialog-warning" onCancel={(e) => { e.preventDefault(); dispatch({ type: 'closeModal' }) }} onClick={(e) => { if (e.target === e.currentTarget) dispatch({ type: 'closeModal' }) }}><form onSubmit={(e) => { e.preventDefault(); dispatch({ type: state.modal === 'contact' ? 'simulateContact' : state.modal === 'result' ? 'saveResult' : 'saveStage' }) }}><div className="crm-subheading"><span>DENTFLOW / DEMO</span><button className="crm-icon-button" type="button" aria-label="Cerrar diálogo" onClick={() => dispatch({ type: 'closeModal' })}><X size={20} /></button></div><h3 id="crm-dialog-title">{state.modal === 'contact' ? 'Preparar contacto' : state.modal === 'result' ? 'Registrar resultado' : 'Actualizar etapa'}</h3><p>{row.name} · {row.treatment}</p><p id="crm-dialog-warning" className="crm-demo-warning">Demo: no se enviará ningún mensaje real</p>{state.modal === 'contact' ? <div className="crm-message">Hola, {row.name.split(' ')[0]}. Recibimos tu consulta sobre {row.treatment.toLowerCase()}. ¿Querés que coordinemos una cita para conversar con el equipo?</div> : <><label>{state.modal === 'result' ? '¿Qué pasó con la consulta?' : 'Próxima etapa'}<select value={state.modal === 'result' ? state.outcome : state.targetStage} onChange={(e) => dispatch(state.modal === 'result' ? { type: 'outcome', value: e.target.value as Outcome } : { type: 'targetStage', value: e.target.value as Stage })}>{state.modal === 'result' ? <><option value="no_response">No respondió</option><option value="contacted">Contactado</option>{['lead', 'contacted', 'scheduled'].includes(row.stage) && <option value="scheduled">Agendó cita</option>}<option value="lost">No está interesado</option></> : <>{nextStage(row) && <option value={nextStage(row)!}>{stageLabels[nextStage(row)!]}</option>}<option value="lost">No está interesado</option></>}</select></label>{needsAppointment && <label>Fecha y hora de la cita<input type="datetime-local" required value={state.appointment} onChange={(e) => dispatch({ type: 'appointment', value: e.target.value })} /><small>Hora de Paraguay. Posterior al reloj de la demo: {formatDate(demoClock(state))} de 2026.</small></label>}</>}{state.error && <p className="crm-error" role="alert">{state.error}</p>}<div className="crm-actions"><button className="crm-button crm-button--primary" type="submit">{state.modal === 'contact' ? 'Simular envío' : 'Guardar resultado'} <Check size={16} /></button><button className="crm-button" type="button" onClick={() => dispatch({ type: 'closeModal' })}>Cancelar</button></div></form></dialog>
}

export function DentFlowDemo({ state, dispatch }: Props) {
  const tabs = useRef<(HTMLButtonElement | null)[]>([])
  const row = state.consultations.find((item) => item.id === state.selectedId)
  return <div className="gallery crm" id="demo-crm" data-animate><div className="gallery-topline"><span className="gallery-index">EXPLORÁ DENTFLOW</span><span className="gallery-note">Demo interactiva · Datos ficticios</span></div><div className="crm-toolbar"><div><strong>DentFlow<span className="crm-brand-dot">.</span></strong><span>Tu operación, en contexto.</span></div><div className="crm-actions"><button className="crm-button" onClick={() => dispatch({ type: 'startTour' })}>Ver recorrido guiado</button><button className="crm-button" onClick={() => { dispatch({ type: 'reset' }); tabs.current[0]?.focus() }}><RotateCcw size={15} /> Reiniciar demo</button></div></div><div className="crm-nav" role="tablist" aria-label="Vistas de DentFlow">{views.map(({ id, label, icon: Icon }, index) => <button ref={(el) => { tabs.current[index] = el }} key={id} id={`demo-tab-${id}`} role="tab" aria-selected={state.view === id} aria-controls="demo-panel" tabIndex={state.view === id ? 0 : -1} onClick={() => dispatch({ type: 'navigate', view: id })} onKeyDown={(e) => tabKey(e, index, views.length, (next) => { dispatch({ type: 'navigate', view: views[next].id as View }); tabs.current[next]?.focus() })}><Icon size={18} /><span>{label}</span></button>)}</div>{state.tour && <aside className="crm-guide" aria-label="Recorrido guiado"><div><span>PASO {Math.min(state.tour.step + 1, 6)} / 6</span><p>{guide[state.tour.step]}</p></div><div className="crm-actions"><button className="crm-button" onClick={() => dispatch({ type: 'restartTour' })}>Reiniciar recorrido</button><button className="crm-icon-button" aria-label="Cancelar recorrido guiado" onClick={() => dispatch({ type: 'cancelTour' })}><X size={18} /></button></div></aside>}<div className="crm-status" role="status" aria-live="polite"><Check size={15} aria-hidden="true" />{state.notice}</div><div id="demo-panel" role="tabpanel" aria-labelledby={`demo-tab-${state.view}`} tabIndex={0} className="crm-body"><div className="crm-view" key={row?.id ?? state.view}>{row ? <Detail state={state} dispatch={dispatch} consultation={row} /> : state.view === 'summary' ? <Summary state={state} dispatch={dispatch} /> : state.view === 'analysis' ? <Analysis state={state} dispatch={dispatch} /> : <PatientList state={state} dispatch={dispatch} pending={state.view === 'pending'} />}</div></div><div className="crm-footnote"><span>Entorno de prueba · Sin conexión al CRM privado</span><span>Reloj simulado: {formatDate(demoClock(state))} de 2026 · PY</span></div><ActionDialog state={state} dispatch={dispatch} /></div>
}
